Server:
  Router: "/ws"
  Port: ":8011"
  PingTimeOut: 5 #s
WebServer:
  Port: "8099"
Database:
  Host: "127.0.0.1"
  Port: "3306"
  UserName: "root"
  Password: "lxy196914"
  DatabaseName: "thewhite"
  MaxIdleConns: 10
  MaxOpenConns: 50
  ConnMaxLifetime: 60 #minute
  Dsn: "root:lxy196914@tcp(127.0.0.1:3306)/thewhite?charset=utf8&multiStatements=true"
Message:
  FileMax: 120 # m
  ContentMaxLen: 500
  SendTimeOut: 60
  RevokeTtimeOut: 120
Mail:
  Host: "smtp.163.com"
  Account: "thesmallwhiteme@163.com"
  Password: "LRNJNXDWUZXDAZUE"
  Port: "465"
Redis:
  Addr: "120.26.1.206:6379"
  Port: 6379
  Password: "wxigNQxrwMm3rECCDAJBdtoO7gxHTnwd"

