message:
  status:
    sending: 1
    success: 2
    error: 3
    haveread: 4
  file_max: 120 # m
  content_max_len: 500
  send_time_out: 60
  revoke_time_out: 120
client:
  ping_time_out: 5 #s
server:
  router: "/ws"
  port: ":8011"


